### ISSUE TITLE
Parse each structure separately

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/opengex#44]
Piston-Meta has the limitation that the entire source must be in memory. For large scenes this can be a limitation. The OpenGEX format is designed as a list of structures, which means that it could be split up into smaller parts. This could also be used to parse in parallel.

An idea is to tell how much memory and how many threads you want to use when reading. The memory tells how much of the source you want to store in memory. It could balance the two, choosing the least constraint.

**Comment by Binero** [comment]
This still seems very suboptimalal. I am also quite ignorant on wether this is even possible. Does the meta library allow to catch a structure without loading the entire file in memory? Surely if it cannot parse a structure, it cannot find one without parsing it either. 

I propose two alternatives:
- fixing the limitation in the meta library
- writing a lexer-parser based reader for the OpenDDL format

**Comment by bvssvni** [comment]
Writing a lexer-parser based reader seems a good way to solve this. I believe that OpenDDL only need one token look-ahead.

**Comment by Binero** [comment]
If that's the way we're going, I suggest putting it in a different crate?

**Comment by Binero** [comment]
Further discussion of parsing should be done in #45.
