### ISSUE TITLE
The Meta Table plan

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/opengex#50]
Alternative to https://github.com/PistonDevelopers/opengex/issues/47.

The idea is that since we already have the piston-meta syntax, and the OpenGEX format might not be suited for editors or data oriented design, we could do the following:
1. Parse the format into meta-data.
2. Use the table library to build a meta table of where to get nodes in the meta data.
3. Add convenience methods for converting specific data.
### Motivation

The table library provides a way to do dynamical data. The same structure can be reused to do transformations while preserving the relationships between the nodes. By using a `usize` to point into meta data, it is possible to do the transformation before converting the data needed.

Since re-reading a format always give the same meta data, the meta table can be built and kept in memory while the meta data is erased. When the data is needed, one can read the format again, but this time without building a meta table.

If you are only interested in specific parts such as meshes, one can either read directly from the meta data or use the meta table to find the place.

It is also possible to use the ranges from the meta data to read directly from the file.

**Comment by Binero** [comment]
Using this kind of representation would require having a lot of enums.

**Comment by bvssvni** [comment]
Closing in favor of https://github.com/PistonDevelopers/opengex/issues/47 for now.
