### ISSUE TITLE
Change Bézier to Bezier

### ISSUE THREAD

**Issue by warmwaffles** [PistonDevelopers/opengex#57]
I keep getting this error

```
/home/warmwaffles/.cargo/registry/src/github.com-88ac128001ac3a9a/piston-opengex-0.4.0/src/lib.rs:4:1: 4:30 error: #[feature] may not be used on the stable release channel
/home/warmwaffles/.cargo/registry/src/github.com-88ac128001ac3a9a/piston-opengex-0.4.0/src/lib.rs:4 #![feature(non_ascii_idents)]
                                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I remove the `é` and the problem goes away. I know Bézier is the proper name, but in most libraries I have seen, usually an `e` is used in place for `é`.

**Comment by Binero** [comment]
Feel free to submit a PR. May I ask what you are using the library for?

**Comment by warmwaffles** [comment]
I am tinkering with gl-rs, etc... I have a few 3d models I wanted to load up and render and the ogex format is one that blender can export for me.
